#Docker-Compose nodes

version: '3.9'
name: nodes
services:

  node1:
    image: node1
    build: ./node
    container_name: node1
    ports:
    - 8084:8080
    networks:
      - network-1
    environment:
      - REST_URL=http://rest:8080
      - NATION=FR

  node2:
    image: node2
    build: ./node
    container_name: node2
    ports:
    - 8084:8080
    networks:
      - network-2

  node3:
    image: node3
    build: ./node
    container_name: node3
    ports:
    - 8084:8080
    networks:
      - network-3

  broadcast:
    image: rabbitmq
    build: ./rabbitmq
    container_name: rabbitmq
    ports:
      - 8086:8080

networks:
  network-fra:
    name: rabbitmq
    external: true


volumes:
  pgdata: {}