#Docker-Compose nodes

version: '3.9'
name: nodes

networks:
  pbft:
    driver: bridge

services:

  rabbit:
    image: rabbit
    build: ./rabbitmq
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pbft

  node1:
    image: node1
    build: ./node
    container_name: node1
    depends_on:
      rabbit:
        condition: service_healthy
    networks:
      - pbft
    volumes:
      - ./node/data/node1:/data

  node2:
    image: node2
    build: ./node
    container_name: node2
    depends_on:
      rabbit:
        condition: service_healthy
    networks:
      - pbft
    volumes:
      - ./node/data/node2:/data

  node3:
    image: node3
    build: ./node
    container_name: node3
    depends_on:
      rabbit:
        condition: service_healthy
    networks:
      - pbft
    volumes:
      - ./node/data/node3:/data

  node4:
    image: node4
    build: ./node
    container_name: node4
    depends_on:
      rabbit:
        condition: service_healthy
    networks:
      - pbft
    volumes:
      - ./node/data/node4:/data