version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"  # RabbitMQ AMQP port
      - "15672:15672"  # RabbitMQ management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persist RabbitMQ data
    environment:
      RABBITMQ_DEFAULT_USER: "guest"  # Default username
      RABBITMQ_DEFAULT_PASS: "guest"  # Default password

volumes:
  rabbitmq_data:
    driver: local
